#!/usr/bin/env bash
args=()
while [ -n "$1" ]; do
    if [ "$1" == '--device' ]; then
        shift
        device="$1";
    else
        args+=("$1")
    fi

    shift
done

if [ -z "${device}" ]; then
    echo "--device <NAME> is required. Run 'aplay -L' for a list (prefer plughw: devices)."
    exit 1
fi

if [ -z "${command}" ]; then
    command = "aplay -D ${device} -r 22050 -c 1 -f S16_LE -t raw"
fi

/app/script/run \
    --uri tcp://0.0.0.0:10601 \
    --program "${command}" \
    --rate 22050  \
    --width 2 \
    --channels 1 "${args[@]}"
 